var num1 = .5;
var num2 = -3;
var num3 = 27;
var num4 = 7;
var string1 = "matt";
var string2 = "fleming";
var string3 = "dojo";
var imHungry = false;
var imFull = true;
var x;
console.log("first number:", num1);
console.log("second number:", num2);
console.log("third number:", num3);
console.log("fourth number", num4);
console.log("first string:", string1);
console.log("second string", string2);
console.log("third string", string3);
console.log("false boolean", imHungry);
console.log("true boolean", imFull);
console.log("undefined variable", x);
